services:

  backend:
    build: .
    container_name: django_backend
    command: >
      sh -c "python manage.py migrate && gunicorn --workers 3 --bind 0.0.0.0:80>
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true


