# Generated by Django 5.2.4 on 2025-08-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='게시판 이름')),
                ('description', models.CharField(max_length=255, verbose_name='게시판 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='게시글 생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='게시글 수정 일시')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판 목록',
                'db_table': 'boards',
            },
        ),
    ]
