# Generated by Django 5.2.5 on 2025-08-18 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('profile_image', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('social_provider', models.CharField(blank=True, max_length=20, null=True)),
                ('social_id', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='user', max_length=25)),
                ('is_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='OzKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('tag_number', models.IntegerField(null=True, verbose_name='기수')),
                ('tag_class', models.CharField(max_length=50, null=True, verbose_name='클래스')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='users_ozkey_is_acti_611d95_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oz_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ozkey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOzkeyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oz_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ozkey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'oz_key')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='oz_keys',
            field=models.ManyToManyField(related_name='users', through='users.UserOzkeyMap', to='users.ozkey'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('social_provider', 'social_id'), name='social_provider_socialid'),
        ),
    ]
