# Generated by Django 5.2.4 on 2025-08-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ozkey',
            old_name='tag_class',
            new_name='tag_classes',
        ),
    ]
