# Generated by Django 5.2.5 on 2025-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_ozkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozkey',
            name='tag_class',
            field=models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend')], max_length=50, null=True, verbose_name='클래스'),
        ),
    ]
