# Generated by Django 5.2.5 on 2025-08-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_seed_ozkey_fe"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userozkeymap",
            unique_together=set(),
        ),
    ]
