server {
    listen 80;
    server_name api.ozboard.shop;
    server_tokens off;

    # certbot에서 유효한지 확인
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # path
    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.ozboard.shop;
    server_tokens off;

    # SSL
    ssl_certificate /etc/letsencrypt/live/api.ozboard.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.ozboard.shop/privkey.pem;

    # --- 백엔드 API ---
    location / {
        proxy_pass http://ozblind_be-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # CORS Preflight 요청 처리
        if ($request_method = OPTIONS) {
            add_header 'Access-Control-Allow-Origin' 'https://o-zblind-fe-git-develop-ls-projects-b89ad826.vercel.app';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        # CORS 헤더 추가
        add_header 'Access-Control-Allow-Origin' 'https://o-zblind-fe-git-develop-ls-projects-b89ad826.vercel.app';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
        add_header 'Access-Control-Allow-Credentials' 'true';
    }

    # --- 정적 파일 ---
    location /static/ {
        alias /app/static/;
    }

    # --- 미디어 파일 ---
    location /media/ {
        alias /app/media/;
    }
}