
server {
    listen 80;
    server_name api.ozboard.shop;
    server_tokens off;

    # certbot에서 유효한지 확인
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # path
    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.ozboard.shop;
    server_tokens off;

    # SSL
    ssl_certificate /etc/letsencrypt/live/api.ozboard.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.ozboard.shop/privkey.pem;

    # --- 백엔드 API ---
    location / {
        proxy_pass http://ozblind_be-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    # COEP / COOP 헤더
        add_header Cross-Origin-Embedder-Policy require-corp;
        add_header Cross-Origin-Opener-Policy same-origin;
    }



    # --- 정적 파일 ---
    location /static/ {
        alias /app/static/;
    }

    # --- 미디어 파일 ---
    location /media/ {
        alias /app/media/;
    }
}
