# Generated by Django 5.2.4 on 2025-08-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bookmark_cnt',
            new_name='bookmark_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dislikes_cnt',
            new_name='dislike_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes_cnt',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='view_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
