# Generated by Django 5.2.5 on 2025-08-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmark_count',
        ),
        migrations.CreateModel(
            name='BestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField()),
                ('refreshed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'db_table': 'best_post',
                'ordering': ['-view_count'],
            },
        ),
    ]
