name: python CI
# 워크 플로우가 실행될 이벤트
on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]

# 실행될 작업
jobs:
  build-and-test:
    # 실행 환경
    runs-on: ubuntu-latest

    # 작업 순차적 단계
    steps:
      # 저장소의 코드 워크플로우 환경으로 가져옴
      -  uses: actions/checkout@v4

      # python 3.13 버전 설정
      - name: Set up python3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Create and activate virtual environment
        run: |
          uv venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV=$(pwd)/.venv" >> $GITHUB_ENV
          echo "::add-path::$(pwd)/.venv/bin"  

      

      - name: Install dependencies
        shell: bash
        run: uv sync

      # isort black 코드 포맷 검사
      - name: Run isort
        shell: bash
        run: |
          source .venv/bin/activate
          isort . 

      - name: Check Black installation
        shell: bash
        run: |
          source .venv/bin/activate
          python -m black --version

      - name: Run black
        shell: bash
        run: |
          source .venv/bin/activate
          python -m black .  


                


